# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AirbyteCli < Formula
  desc "CLI for Airbyte, designed for use by both humans and agents"
  homepage "https://github.com/airbytehq/airbyte-cli"
  version "0.2.0"
  license "Elastic-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/airbytehq/airbyte-cli/releases/download/v0.2.0/airbyte_0.2.0_darwin_amd64.tar.gz"
      sha256 "b7f4b3bb176766eb6b1979d2b2b001272d2d56ed7dcf48e2d36357447650ad75"

      define_method(:install) do
        bin.install "airbyte"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/airbytehq/airbyte-cli/releases/download/v0.2.0/airbyte_0.2.0_darwin_arm64.tar.gz"
      sha256 "01c8654c87ff12a2aab443adcfe68055c0f59fb4c362171fd977030e7883a330"

      define_method(:install) do
        bin.install "airbyte"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/airbytehq/airbyte-cli/releases/download/v0.2.0/airbyte_0.2.0_linux_amd64.tar.gz"
      sha256 "6a42a8ace52095eccb525209931a5de90d03a281e09191f42aecd9626726ec10"
      define_method(:install) do
        bin.install "airbyte"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/airbytehq/airbyte-cli/releases/download/v0.2.0/airbyte_0.2.0_linux_arm64.tar.gz"
      sha256 "4ffb467f39641e06d4cd9a4d81d3d87f7ab50f14fc9b186012f27d76d044810e"
      define_method(:install) do
        bin.install "airbyte"
      end
    end
  end

  test do
    system "#{bin}/airbyte", "agents", "version"
  end
end
