# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AirbyteAgent < Formula
  desc "CLI for Airbyte Agents, designed for use by both humans and agents"
  homepage "https://github.com/airbytehq/airbyte-agent-cli"
  version "0.1.0"
  license "ELv2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/airbytehq/airbyte-agent-cli/releases/download/v0.1.0/airbyte-agent_0.1.0_darwin_amd64.tar.gz"
      sha256 "4337b531a4afd1fad0ea2548a1e3d56c1f0d0db58d32742771344fc90b1279f9"

      define_method(:install) do
        bin.install "airbyte-agent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/airbytehq/airbyte-agent-cli/releases/download/v0.1.0/airbyte-agent_0.1.0_darwin_arm64.tar.gz"
      sha256 "a201c4be6734c2341916bb781cfebaa60538daec3c4ae2fa2a241b33ccf3157a"

      define_method(:install) do
        bin.install "airbyte-agent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/airbytehq/airbyte-agent-cli/releases/download/v0.1.0/airbyte-agent_0.1.0_linux_amd64.tar.gz"
      sha256 "e8f04f5e6aab0e7d50498ceee99f6071d4296cf9f35d01e406c29e3f82b3bddd"
      define_method(:install) do
        bin.install "airbyte-agent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/airbytehq/airbyte-agent-cli/releases/download/v0.1.0/airbyte-agent_0.1.0_linux_arm64.tar.gz"
      sha256 "7b663fcc50179c2d3ffa93d59576c4099e156057e32abba8722124a4bb43a230"
      define_method(:install) do
        bin.install "airbyte-agent"
      end
    end
  end

  test do
    system "#{bin}/airbyte-agent", "version"
  end
end
