# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AirbyteAgent < Formula
  desc "CLI for Airbyte Agents, designed for use by both humans and agents"
  homepage "https://github.com/airbytehq/airbyte-agent-cli"
  version "0.1.1"
  license "Elastic-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/airbytehq/airbyte-agent-cli/releases/download/v0.1.1/airbyte-agent_0.1.1_darwin_amd64.tar.gz"
      sha256 "332ca039e0852f9776e43ee0d1df1aed72e0f022bbd3200db09786c5370e5aed"

      define_method(:install) do
        bin.install "airbyte-agent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/airbytehq/airbyte-agent-cli/releases/download/v0.1.1/airbyte-agent_0.1.1_darwin_arm64.tar.gz"
      sha256 "f06f867bed4f7bad56c2796ce1badf7d4b179c4ca4a27fab6eea394e15bbd302"

      define_method(:install) do
        bin.install "airbyte-agent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/airbytehq/airbyte-agent-cli/releases/download/v0.1.1/airbyte-agent_0.1.1_linux_amd64.tar.gz"
      sha256 "c81227b3b5317dc2e0c865e5391e0797f6dd4bd5c12e60c0f481d532857a4726"
      define_method(:install) do
        bin.install "airbyte-agent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/airbytehq/airbyte-agent-cli/releases/download/v0.1.1/airbyte-agent_0.1.1_linux_arm64.tar.gz"
      sha256 "74ec156bb815c7b12e2362884acef7ff8d06c7a29e78a9c35312fbdfc1b211f8"
      define_method(:install) do
        bin.install "airbyte-agent"
      end
    end
  end

  test do
    system "#{bin}/airbyte-agent", "version"
  end
end
