# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AirbyteAgents < Formula
  desc "CLI for Airbyte Agents, designed for use by both humans and agents"
  homepage "https://github.com/airbytehq/airbyte-agents-cli"
  version "0.1.0"
  license "ELv2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/airbytehq/airbyte-agents-cli/releases/download/v0.1.0/airbyte-agents_0.1.0_darwin_amd64.tar.gz"
      sha256 "daa8e6b35ea1ca1a13ea23396ecd9bcb771eabf909601a0efd2d47b500ee6bc5"

      define_method(:install) do
        bin.install "airbyte-agents"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/airbytehq/airbyte-agents-cli/releases/download/v0.1.0/airbyte-agents_0.1.0_darwin_arm64.tar.gz"
      sha256 "03aca3fb50ef39da8555a1386ef4caa444529a3c33a76dbc64bbd1512d8558c8"

      define_method(:install) do
        bin.install "airbyte-agents"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/airbytehq/airbyte-agents-cli/releases/download/v0.1.0/airbyte-agents_0.1.0_linux_amd64.tar.gz"
      sha256 "5a24f069d2a0e4ade85881ed365dde96f82528e0456cbb835631647e5f71f41b"
      define_method(:install) do
        bin.install "airbyte-agents"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/airbytehq/airbyte-agents-cli/releases/download/v0.1.0/airbyte-agents_0.1.0_linux_arm64.tar.gz"
      sha256 "fd371f28e03ffa4e3bb174ff952314e3fb405887eb4e789d40daac33959f2dac"
      define_method(:install) do
        bin.install "airbyte-agents"
      end
    end
  end

  test do
    system "#{bin}/airbyte-agents", "version"
  end
end
