# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AirbyteAgents < Formula
  desc "Go CLI for the Airbyte API, designed for both humans and AI agents"
  homepage "https://github.com/airbytehq/airbyte-agents-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/airbytehq/airbyte-agents-cli/releases/download/v0.1.0/airbyte-agents_0.1.0_darwin_amd64.tar.gz"
      sha256 "45daf83be6c83f397d18d3b93109138dd651e961021e77e86fb8ec3a79f6e1bd"

      define_method(:install) do
        bin.install "airbyte-agents"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/airbytehq/airbyte-agents-cli/releases/download/v0.1.0/airbyte-agents_0.1.0_darwin_arm64.tar.gz"
      sha256 "f8a682616cae60ee71bb1af4d49fe1120bb9bcd02baf39d1bcdb1c6637f0de31"

      define_method(:install) do
        bin.install "airbyte-agents"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/airbytehq/airbyte-agents-cli/releases/download/v0.1.0/airbyte-agents_0.1.0_linux_amd64.tar.gz"
      sha256 "f11f1db7450781033a9c2ce926e220d2e68cc53b757fad6eed7f79dd3c9b54dd"
      define_method(:install) do
        bin.install "airbyte-agents"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/airbytehq/airbyte-agents-cli/releases/download/v0.1.0/airbyte-agents_0.1.0_linux_arm64.tar.gz"
      sha256 "83b1ed9640cc5bd462da1aabae65eff815f6826f063281c08c3590259ab4b40a"
      define_method(:install) do
        bin.install "airbyte-agents"
      end
    end
  end

  test do
    system "#{bin}/airbyte-agents", "version"
  end
end
