# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AirbyteAgent < Formula
  desc "CLI for Airbyte Agents, designed for use by both humans and agents"
  homepage "https://github.com/airbytehq/airbyte-agent-cli"
  version "0.1.0"
  license "Elastic-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/airbytehq/airbyte-agent-cli/releases/download/v0.1.0/airbyte-agent_0.1.0_darwin_amd64.tar.gz"
      sha256 "4dd86f77e347ef2de98d0b39eec2dca1ce3d8669d1ba15a57b1870030c399775"

      define_method(:install) do
        bin.install "airbyte-agent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/airbytehq/airbyte-agent-cli/releases/download/v0.1.0/airbyte-agent_0.1.0_darwin_arm64.tar.gz"
      sha256 "32ce70226e05ff180bca1515057969be4495a49356d9cc4846fadea4762539af"

      define_method(:install) do
        bin.install "airbyte-agent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/airbytehq/airbyte-agent-cli/releases/download/v0.1.0/airbyte-agent_0.1.0_linux_amd64.tar.gz"
      sha256 "cf9ea3e056661f3e3cb95b68cd6c63e62e60e7b849e9228b854ce02d59c7945c"
      define_method(:install) do
        bin.install "airbyte-agent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/airbytehq/airbyte-agent-cli/releases/download/v0.1.0/airbyte-agent_0.1.0_linux_arm64.tar.gz"
      sha256 "bfe26f01ee063677a31625a500ee05431f94c2d6d1165a3077ca0e1f8778a10d"
      define_method(:install) do
        bin.install "airbyte-agent"
      end
    end
  end

  test do
    system "#{bin}/airbyte-agent", "version"
  end
end
